const baza = {
    uzum:[
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2KZkkWp-uEMx9ezQpVKpJAp9TiGn-Q-tdDO53tp1PViZhdlmk2aMTcVpAmuQYRsYkAbA&usqp=CAU',
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        }
    ],
    yandex:[
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5H4CJITE7wk_Ap3hMd6oNhjSpmDcw86NvYA&s',
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
    ],
    lavka:[
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDm9a2zeYwFlMnFbTjDHOtvBdFRwCqiGPIMg&s',
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        }
    ],
    apex:[
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvxeAXAauXIylYqbvyjwpd1-y0nqnxMOWAODpaJ5amtNJZoRgkTo86hGlwI5P3vkKI-Qc&usqp=CAU',
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        }
    ],
    bbq:[
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJikbl-TT4pJPH3oarc2YQ69Hd2s7NcgElMw&s',
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        }
    ],
    embassy:[
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHsSkvxyVd80jpm6aJXMcQL9WZZ3n6o9ZuKTUF0Uo_7V52DFCJR_3bKvi7ZiMrbbSJWTU&usqp=CAU',
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        }
    ],
    bellissimo:[
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7D0z5XExjtdF6wkNN-XtKBC4qRbmi3zUXdg&s',
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        }
    ],
    dodo:[
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnLpp50VEphmptQoT_1hgfVm7qxkz8Ekkomw&s',
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        }
    ],
    evos:[
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ9I1L1CyG-I14sqK7mR2fOoUm_YaDrfX38Q&s',
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        }
    ],
    kfc:[
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbqijoaA-vmE8nOGx5ebvbjVB2eDDuN9dnGg&s',
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        },
        {
            text:'promokod',
            prom:'promokod',
        }
    ],
}

export default baza

